apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: ns_name
spec:
  parentRefs:
    - name: zeus-gw
      sectionName: https
      namespace: envoy-gateway-system
  hostnames:
    - "backend.zeus"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/backend"
      backendRefs:
        - name: backend
          namespace: phrases
          port: 7070
