apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/adhatcher/random_phrase_api'
    targetRevision: HEAD
    path: kube/kustomize/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: phrases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true 
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-api-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: 'https://github.com/adhatcher/random_phrase_api'
  name: backend-app-repo