apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/adhatcher/random-phrase-app'
    targetRevision: HEAD
    path: kube/kustomize/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: phrases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true 